### ISSUE TITLE
Scientific Program page bullet lists, items are too far apart

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/dynamics-evolution-indico#12]
Currently looks like this:
![Screenshot from 2022-09-30 17-15-55](https://user-images.githubusercontent.com/1109328/193357397-86930862-5fb7-48c9-826f-8e051ece941a.png)

This looks better if I turn off `margin-top` in the CSS:
```css
ul.tracks li {
    color: #555;
    /* margin-top: 2em; */
}
```

![Screenshot from 2022-09-30 17-17-21](https://user-images.githubusercontent.com/1109328/193357541-c5ad1886-e936-4140-bca1-feeca29b4cbf.png)
