### ISSUE TITLE
Scientific program format is janky

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/dynamics-evolution-indico#17]
`<ul>` elements have way too much space between items:
<img  width=600 src="https://github.com/ArtPoon/dynamics-evolution-indico/assets/1109328/eccdba3e-17dc-4e11-923b-55466cc67ff3"/>

This is controlled by the following lines in `_tracks.scss`:
```css
ul.tracks li {
  color: #555;
  margin-top: 2em;
}
```
Deactivating `margin-top` looks much better:
<img width=600 src="https://github.com/ArtPoon/dynamics-evolution-indico/assets/1109328/7f55ed68-f501-4356-837d-05d74df238d6"/>
